// <auto-generated />
using System;
using Barberia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barberia.Migrations
{
    [DbContext(typeof(BarberiaContext))]
    [Migration("20251121090912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Barberia.Models.Domain.BarberoServicio", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId", "ServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("BarberoServicios");

                    b.HasData(
                        new
                        {
                            EmpleadoId = 2,
                            ServicioId = 1
                        },
                        new
                        {
                            EmpleadoId = 2,
                            ServicioId = 2
                        },
                        new
                        {
                            EmpleadoId = 2,
                            ServicioId = 3
                        },
                        new
                        {
                            EmpleadoId = 3,
                            ServicioId = 3
                        },
                        new
                        {
                            EmpleadoId = 3,
                            ServicioId = 4
                        },
                        new
                        {
                            EmpleadoId = 3,
                            ServicioId = 1
                        },
                        new
                        {
                            EmpleadoId = 4,
                            ServicioId = 5
                        },
                        new
                        {
                            EmpleadoId = 4,
                            ServicioId = 6
                        },
                        new
                        {
                            EmpleadoId = 4,
                            ServicioId = 1
                        });
                });

            modelBuilder.Entity("Barberia.Models.Domain.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            PersonaId = 1
                        },
                        new
                        {
                            Id = 3,
                            PersonaId = 2
                        },
                        new
                        {
                            Id = 4,
                            PersonaId = 3
                        });
                });

            modelBuilder.Entity("Barberia.Models.Domain.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Confirmado"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cancelado"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Reservado"
                        });
                });

            modelBuilder.Entity("Barberia.Models.Domain.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("EsBarbero")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Gómez",
                            CorreoElectronico = "juan@barberia.local",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsBarbero = true,
                            Nombre = "Juan",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Pérez",
                            CorreoElectronico = "mario@barberia.local",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsBarbero = true,
                            Nombre = "Mario",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rodríguez",
                            CorreoElectronico = "luis@barberia.local",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsBarbero = true,
                            Nombre = "Luis",
                            UsuarioId = 4
                        });
                });

            modelBuilder.Entity("Barberia.Models.Domain.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Corte tradicional con tijera y máquina.",
                            Nombre = "Corte clásico",
                            Precio = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Fade bajo, medio o alto, con terminaciones a navaja.",
                            Nombre = "Corte degradado (Fade)",
                            Precio = 6500m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Perfilado, rebaje y prolijo general.",
                            Nombre = "Arreglo de barba",
                            Precio = 3500m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Afeitado con toalla caliente y navaja.",
                            Nombre = "Afeitado clásico",
                            Precio = 4500m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Coloración tradicional para cabello.",
                            Nombre = "Tintura para cabello",
                            Precio = 9000m
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Coloración y perfilado de barba.",
                            Nombre = "Tintura para barba",
                            Precio = 6000m
                        });
                });

            modelBuilder.Entity("Barberia.Models.Domain.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaBloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EstaEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Contrasena = "HASH_JUAN",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsAdmin = false,
                            EstaBloqueado = false,
                            EstaEliminado = false,
                            NombreUsuario = "juan"
                        },
                        new
                        {
                            Id = 3,
                            Contrasena = "HASH_MARIO",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsAdmin = false,
                            EstaBloqueado = false,
                            EstaEliminado = false,
                            NombreUsuario = "mario"
                        },
                        new
                        {
                            Id = 4,
                            Contrasena = "HASH_LUIS",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsAdmin = false,
                            EstaBloqueado = false,
                            EstaEliminado = false,
                            NombreUsuario = "luis"
                        });
                });

            modelBuilder.Entity("Barberia.Models.Domain.BarberoServicio", b =>
                {
                    b.HasOne("Barberia.Models.Domain.Empleado", "Empleado")
                        .WithMany("BarberoServicios")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Barberia.Models.Domain.Servicio", "Servicio")
                        .WithMany("BarberoServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Empleado", b =>
                {
                    b.HasOne("Barberia.Models.Domain.Persona", "Persona")
                        .WithOne("Empleado")
                        .HasForeignKey("Barberia.Models.Domain.Empleado", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Persona", b =>
                {
                    b.HasOne("Barberia.Models.Domain.Usuario", "Usuario")
                        .WithOne("Persona")
                        .HasForeignKey("Barberia.Models.Domain.Persona", "UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Reserva", b =>
                {
                    b.HasOne("Barberia.Models.Domain.Estado", "Estado")
                        .WithMany("Reservas")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Barberia.Models.Domain.Servicio", "Servicio")
                        .WithMany("Reservas")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Barberia.Models.Domain.Turno", "Turno")
                        .WithMany("Reservas")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Barberia.Models.Domain.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Servicio");

                    b.Navigation("Turno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Turno", b =>
                {
                    b.HasOne("Barberia.Models.Domain.Empleado", "Empleado")
                        .WithMany("Turnos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Empleado", b =>
                {
                    b.Navigation("BarberoServicios");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Estado", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Persona", b =>
                {
                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Servicio", b =>
                {
                    b.Navigation("BarberoServicios");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Turno", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Barberia.Models.Domain.Usuario", b =>
                {
                    b.Navigation("Persona");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
